import type { Metadata } from 'next';
import { Encode_Sans_Expanded, Reddit_Sans } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/header';
import TopBanner from '@/components/layout/top-banner';

const mainFont = Reddit_Sans({
  variable: '--font-main',
  subsets: ['latin'],
});

const displayFont = Encode_Sans_Expanded({
  variable: '--font-display',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mainFont.variable}  ${displayFont.variable} antialiased`}
      >
        <TopBanner />
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
